mg_gestion_clients:
    resource: "@MGGestionBundle/Controller/clientsController.php"
    type:     annotation

mg_gestion_projet:
    resource: "@MGGestionBundle/Controller/projetController.php"
    type:     annotation

mg_user:
    resource: "@MGUserBundle/Resources/config/routing.yml"
    prefix:   /

mg_gestion:
    resource: "@MGGestionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
