# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

# app/config/services.yml
#services:
 #   mg_user.form.registration:
  #      class: MG\UserBundle\Form\RegistrationType
   #     tags:
    #        - { name: form.type, alias: mg_user_registration }
