mg_gestion_homepage:
    path:     /
    defaults: { _controller: MGGestionBundle:Default:index }


index:
  path:    /index
  defaults:    {_controller: MGGestionBundle:Advert:index}


dashboard:
  path:    /dashboard
  defaults:    {_controller: MGGestionBundle:Dashboard:dashboard}


graphic:
  path:    /graphic
  defaults:    {_controller: MGGestionBundle:Graphic:graphic}

