<?php

namespace MG\GestionBundle\Repository;

/**
 * clientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientsRepository extends \Doctrine\ORM\EntityRepository
{
}
