<?php

namespace MG\GestionBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * clientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientsRepository extends \Doctrine\ORM\EntityRepository
{
  public function getClientsWithProjet()
  {
    $qb = $this->createQueryBuilder('c');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->join('p.clients', 'c')
      ->addSelect('c')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('c.name'));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

}
