<?php

namespace MG\GestionBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * clientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClient($user)
    {
        return $this->createQueryBuilder('cli')
            ->join('cli.user', 'u')
            ->where('u.id = :user_id')
            ->orderBy('cli.created', 'DESC')
            ->setMaxResults(3)
            ->setParameter('user_id', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
